# Modes:
# - "islands"     - server with player island worlds
# - "lobby"       - server with spawn (for hub, shops etc.)
mode: "islands"
debug: true
islands:
  # How many island worlds can be loaded at once. 0 for no limit.
  worlds-limit: 0